---

- name: assert | Test if bareos_sd_hostname is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_hostname is defined
      - bareos_sd_hostname is string
      - bareos_sd_hostname is not none
    quiet: yes

- name: assert | Test if bareos_sd_tls_enable is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_tls_enable is defined
      - bareos_sd_tls_enable is boolean
    quiet: yes

- name: assert | Test if bareos_sd_tls_verify_peer is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_tls_verify_peer is defined
      - bareos_sd_tls_verify_peer is boolean
    quiet: yes

- name: assert | Test if bareos_sd_directors is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_directors is iterable
    quiet: yes
  when:
    - bareos_sd_directors is defined

- name: assert | Test if items in bareos_sd_directors are set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name is not none
      - item.password is defined
      - item.password is string
      - item.password is not none
    quiet: yes
  loop: "{{ bareos_sd_directors }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_directors is defined

- name: assert | Test if tls_enable in bareos_sd_directors is set correctly
  ansible.builtin.assert:
    that:
      - item.tls_enable is boolean
    quiet: yes
  loop: "{{ bareos_sd_directors }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_directors is defined
    - item.tls_enable is defined

- name: assert | Test if tls_verify_peer in bareos_sd_directors is set correctly
  ansible.builtin.assert:
    that:
      - item.tls_verify_peer is boolean
    quiet: yes
  loop: "{{ bareos_sd_directors }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_directors is defined
    - item.tls_verify_peer is defined

- name: assert | Test if bareos_sd_devices is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_devices is iterable
    quiet: yes
  when:
    - bareos_sd_devices is defined

- name: assert | Test if items in bareos_sd_devices are set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name is not none
      - item.media_type is defined
      - item.media_type is string
      - item.media_type is not none
      - item.archive_device is defined
      - item.archive_device is string
      - item.archive_device is not none
      - item.label_media is defined
      - item.label_media is boolean
      - item.random_access is defined
      - item.random_access is boolean
      - item.automatic_mount is defined
      - item.automatic_mount is boolean
      - item.removable_media is defined
      - item.removable_media is boolean
      - item.always_open is defined
      - item.always_open is boolean
    quiet: yes
  loop: "{{ bareos_sd_devices }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_devices is defined

- name: assert | Test if bareos_sd_messages is set correctly
  ansible.builtin.assert:
    that:
      - bareos_sd_messages is iterable
    quiet: yes
  when:
    - bareos_sd_messages is defined

- name: assert | Test if items in bareos_sd_messages are set correctly
  ansible.builtin.assert:
    that:
      - item.name is defined
      - item.name is string
      - item.name is not none
      - item.description is defined
      - item.description is string
      - item.description is not none
    quiet: yes
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_messages is defined

- name: assert | Test if item.director in bareos_sd_messages are set correctly
  ansible.builtin.assert:
    that:
      - item.director is mapping
      - item.director.server is defined
      - item.director.server is string
      - item.director.server is not none
      - item.director.messages is defined
      - item.director.messages is iterable
    quiet: yes
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_messages is defined
    - item.director is defined

- name: assert | Test if item.append in bareos_sd_messages are set correctly
  ansible.builtin.assert:
    that:
      - item.append is mapping
      - item.append.file is defined
      - item.append.file is string
      - item.append.file is not none
      - item.append.messages is defined
      - item.append.messages is iterable
    quiet: yes
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_messages is defined
    - item.append is defined

- name: assert | Test if item.console in bareos_sd_messages are set correctly
  ansible.builtin.assert:
    that:
      - item.console is iterable
    quiet: yes
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - bareos_sd_messages is defined
    - item.console is defined
