---
# tasks file for bareos_sd

- name: Include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Install packages
  ansible.builtin.package:
    name: "{{ bareos_sd_packages }}"

- name: Place bareos-sd.conf
  ansible.builtin.template:
    src: bareos-sd.conf.j2
    dest: "/etc/bareos/bareos-sd.d/storage/bareos-sd.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  notify:
    - Restart bareos-sd

- name: Place director
  ansible.builtin.template:
    src: director.conf.j2
    dest: "/etc/bareos/bareos-sd.d/director/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_directors }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart bareos-sd
  when:
    - bareos_sd_directors is defined

- name: Place device
  ansible.builtin.template:
    src: device.conf.j2
    dest: "/etc/bareos/bareos-sd.d/device/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_devices }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart bareos-sd
  when:
    - bareos_sd_devices is defined

- name: Place message
  ansible.builtin.template:
    src: message.conf.j2
    dest: "/etc/bareos/bareos-sd.d/messages/{{ item.name }}.conf"
    owner: bareos
    group: bareos
    mode: "0640"
    backup: "{{ bareos_sd_backup_configurations }}"
  loop: "{{ bareos_sd_messages }}"
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Restart bareos-sd

- name: Start bareos-sd
  ansible.builtin.service:
    name: bareos-sd
    state: started
    enabled: yes
