---
# handlers file for bareos_sd

- name: Check configuration
  ansible.builtin.command: "/usr/sbin/bareos-sd --test-config"
  changed_when: no

- name: Restart bareos-sd
  ansible.builtin.service:
    name: bareos-sd
    state: restarted
