---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-bareos_sd
      bareos_sd_directors:
        - name: dir-1
          password: "somepassword"
      bareos_sd_messages:
        - name: "Standard"
          director: "dir-1 = all, !skipped, !restored"
          description: "Send all messages to the Director."
          append:
            file: "/var/log/bareos/bareos.log"
            messages:
              - all
              - "!skipped"
              - "!terminate"
      bareos_sd_devices:
        - name: "FileStorage"
          media_type: "File"
          archive_device: "/var/lib/bareos/storage"
          label_media: yes
          random_access: yes
          automatic_mount: yes
          removable_media: no
          always_open: no
          description: "File device. A connecting Director must have the same Name and MediaType."
