---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.bareos_repository
      bareos_repository_enable_tracebacks: yes
