---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if port 9103 is listening
      ansible.builtin.wait_for:
        port: 9103

    - name: Test configuration for warnings
      ansible.builtin.command:
        cmd: bareos-sd --test-config
      become_user: bareos
      register: bareos_sd_test_config
      failed_when:
        - bareos_sd_test_config.stdout_lines is search("There are configuration warnings")
