---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9103 is listening
      ansible.builtin.wait_for:
        port: 9103

    - name: Test configuration
      ansible.builtin.command:
        cmd: bareos-sd --test-config
