---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Check if port 9103 is listening
      ansible.builtin.wait_for:
        port: 9103
    # Maybe add a Director, bconsole and see of the Storage Daemon is connected.
